---
- name: Add php repo
  apt_repository:
    repo: "{{ php_repo }}"
    update_cache: yes
    state: present

- name: Install php
  apt:
    state: latest
    name: "{{ item }}"
  with_items: "{{ php_packages }}"

- name: Install php custom packages
  apt:
    state: latest
    name: "{{ item }}"
  with_items: "{{ php_packages_custom|default(omit) }}"
  when: php_packages_custom is defined
